### ISSUE TITLE
code doesn't run and says it can't connect to the display

### ISSUE THREAD

**Issue by kzphys** [jordissm/tutorial#1]
Traceback (most recent call last):
  File "ho_solver_v1.0.0.py", line 92, in <module>
    fig, ax = plt.subplots(1,3,figsize=[15,5],gridspec_kw={'wspace':.4})
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 1202, in subplots
    fig = figure(**fig_kw)
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 539, in figure
    figManager = new_figure_manager(num, figsize=figsize,
  File "/usr/lib/python3/dist-packages/matplotlib/backend_bases.py", line 3259, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/_backend_tk.py", line 950, in new_figure_manager_given_figure
    window = tk.Tk(className="matplotlib")
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2270, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "127.0.0.1:0"

**Comment by kzphys** [comment]
This issue was solved by modifying the bashrc file with 
`export DISPLAY=$(awk '/nameserver/{print $2; exit}' /etc/resolv.conf 2>/dev/null):0
export LIBGL_ALWAYS_INDIRECT=1`
which allowed the .png file to be generated.
